import {
  type LucideIcon,
  Command,
  Loader2,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  X,
  Trash2,
  FileText,
  LucideImage,
  Settings,
  CreditCard,
  PlusCircle,
  AlertTriangle,
  User,
  ArrowRight,
  ArrowLeft,
  HelpCircle,
  SunMedium,
  Moon,
  Laptop,
  Twitter,
  Github,
  Linkedin,
  Mail,
  Copy,
  Check,
  Search,
  Info,
  XCircle,
  CheckCircle2,
  UploadCloud,
  Calendar,
  DollarSign,
  BarChart2,
  Users,
  Briefcase,
  MessageSquare,
  Bell,
  Eye,
  EyeOff,
  Menu,
  ExternalLink,
  Filter,
  List,
  Grid,
  Home,
  ShoppingCart,
  Package,
  ShieldCheck,
  Lock,
  LucideLink,
  MapPin,
  Phone,
  Globe,
  Star,
  Heart,
  Bookmark,
  Share2,
  Download,
  Printer,
  Archive,
  Send,
  Sliders,
  Zap,
  Award,
  Gift,
  Key,
  Tag,
  ThumbsUp,
  ThumbsDown,
  Clock,
  Save,
  Folder,
  File,
  Database,
  Server,
  Cloud,
  HardDrive,
  Cpu,
  GitBranch,
  GitCommit,
  GitMerge,
  GitPullRequest,
  Terminal,
  Code,
  BookOpen,
  ClipboardList,
  TrendingUp,
  TrendingDown,
  PieChart,
  TargetIcon,
  Navigation,
  Compass,
  Anchor,
  LifeBuoy,
  Settings2,
  Wrench,
  Palette,
  LayoutDashboard,
  Newspaper,
  Building,
  Factory,
  Store,
  Receipt,
  Banknote,
  Wallet,
  Landmark,
  Car,
  Train,
  Ship,
  Plane,
  Rocket,
  Bike,
  FootprintsIcon as Walk,
  Accessibility,
  Volume2,
  VolumeX,
  Mic,
  Video,
  Camera,
  Film,
  Music,
  PlayCircle,
  PauseCircle,
  StopCircle,
  SkipForward,
  SkipBack,
  ShuffleIcon,
  RepeatIcon,
  Maximize2,
  Minimize2,
  Fullscreen,
  Move,
  RotateCcw,
  RotateCw,
  ZoomIn,
  ZoomOut,
  AlertCircle,
  ShieldAlert,
  BadgeInfo,
  BadgeCheck,
  BadgeX,
  BadgeHelp,
  Circle,
  Square,
  Triangle,
  Edit3,
  Ellipsis,
  Pizza,
} from "lucide-react"

export type Icon = LucideIcon

export const Icons = {
  logo: Command,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  trash: Trash2,
  post: FileText,
  page: FileText,
  media: LucideImage,
  settings: Settings,
  billing: CreditCard,
  ellipsis: Ellipsis,
  add: PlusCircle,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  help: HelpCircle,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  twitter: Twitter,
  gitHub: Github,
  linkedin: Linkedin,
  mail: Mail,
  copy: Copy,
  copyDone: Check,
  search: Search,
  info: Info,
  error: XCircle,
  success: CheckCircle2,
  uploadCloud: UploadCloud,
  calendar: Calendar,
  dollarSign: DollarSign,
  barChart: BarChart2,
  users: Users,
  briefcase: Briefcase,
  messageSquare: MessageSquare,
  bell: Bell,
  eye: Eye,
  eyeOff: EyeOff,
  menu: Menu,
  externalLink: ExternalLink,
  filter: Filter,
  list: List,
  grid: Grid,
  home: Home,
  shoppingCart: ShoppingCart,
  packageIcon: Package, // Renamed to avoid conflict with 'package' keyword
  shieldCheck: ShieldCheck,
  lock: Lock,
  link: LucideLink,
  mapPin: MapPin,
  phone: Phone,
  globe: Globe,
  star: Star,
  heart: Heart,
  bookmark: Bookmark,
  share: Share2,
  download: Download,
  printer: Printer,
  archive: Archive,
  send: Send,
  sliders: Sliders,
  zap: Zap,
  award: Award,
  gift: Gift,
  key: Key,
  tag: Tag,
  thumbsUp: ThumbsUp,
  thumbsDown: ThumbsDown,
  clock: Clock,
  save: Save,
  folder: Folder,
  file: File,
  database: Database,
  server: Server,
  cloud: Cloud,
  hardDrive: HardDrive,
  cpu: Cpu,
  gitBranch: GitBranch,
  gitCommit: GitCommit,
  gitMerge: GitMerge,
  gitPullRequest: GitPullRequest,
  terminal: Terminal,
  code: Code,
  bookOpen: BookOpen,
  clipboardList: ClipboardList,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  pieChart: PieChart,
  target: TargetIcon,
  navigation: Navigation,
  compass: Compass,
  anchor: Anchor,
  lifeBuoy: LifeBuoy,
  settings2: Settings2,
  wrench: Wrench,
  palette: Palette,
  layoutDashboard: LayoutDashboard,
  newspaper: Newspaper,
  building: Building,
  factory: Factory,
  store: Store,
  receipt: Receipt,
  banknote: Banknote,
  wallet: Wallet,
  landmark: Landmark,
  car: Car,
  train: Train,
  ship: Ship,
  plane: Plane,
  rocket: Rocket,
  bike: Bike,
  walk: Walk,
  accessibility: Accessibility,
  volume2: Volume2,
  volumeX: VolumeX,
  mic: Mic,
  video: Video,
  camera: Camera,
  film: Film,
  music: Music,
  playCircle: PlayCircle,
  pauseCircle: PauseCircle,
  stopCircle: StopCircle,
  skipForward: SkipForward,
  skipBack: SkipBack,
  shuffle: ShuffleIcon,
  repeat: RepeatIcon,
  maximize2: Maximize2,
  minimize2: Minimize2,
  fullscreen: Fullscreen,
  move: Move,
  rotateCcw: RotateCcw,
  rotateCw: RotateCw,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
  alertCircle: AlertCircle,
  shieldAlert: ShieldAlert,
  badgeInfo: BadgeInfo,
  badgeCheck: BadgeCheck,
  badgeX: BadgeX,
  badgeHelp: BadgeHelp,
  circle: Circle,
  square: Square,
  triangle: Triangle,
  edit3: Edit3,
  pizza: Pizza,
}

export type IconName = keyof typeof Icons
